name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: run tests and coverage
      run: |
	docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
	./build.sh
